CREATE table MOVIE(
MPK VARCHAR(20) PRIMARY KEY,
TITLE VARCHAR(100) UNIQUE,
CONTENT VARCHAR(2000) NOT NULL,
MTYPE VARCHAR(20) NOT NULL,
MDATE DATE NOT NULL
);

INSERT INTO MOVIE VALUES('A1001', '샹치', '이러한 내용이다', 'ACTION', SYSDATE);
INSERT INTO MOVIE VALUES('A1002', '샹치2', '이러한 내용이다2', 'ACTION', SYSDATE);

SELECT * FROM MOVIE WHERE TITLE LIKE '%샹%';

